#!/bin/bash
set -eu

NAME=whyolet-font-alphanumericals
# 19x31 -> 19000x31000 / 8 = 2375x3875
inkscape -w 2375 -h 3875 -o $NAME.png $NAME.svg

NAME=whyolet-font-logo
# 37x8 -> 37000x8000 / 8 = 4625x1000
inkscape -w 4625 -h 1000 -o $NAME.png $NAME.svg

